In [1]:
import gym

In [2]:
env = gym.make('CartPole-v0')

In [4]:
for i_episode in range(20):
    obs = env.reset()
    for t in range(100):
        env.render()
        print(obs)
        action = env.action_space.sample()
        obs, reward, done, info = env.step(action)
        if done:
            print('Episode finished after {} timesteps'.format(t+1))
            break

[-0.04939779  0.03014856  0.01049685  0.01618355]
[-0.04879482 -0.16512235  0.01082052  0.31215978]
[-0.05209727  0.02984379  0.01706371  0.02290886]
[-0.05150039  0.22471693  0.01752189 -0.2643418 ]
[-0.04700605  0.02934933  0.01223506  0.0338158 ]
[-0.04641907  0.2242937   0.01291137 -0.25498187]
[-0.04193319  0.41922895  0.00781173 -0.54356452]
[-0.03354861  0.61424025 -0.00305956 -0.83377593]
[-0.02126381  0.80940387 -0.01973507 -1.1274195 ]
[-0.00507573  1.00477874 -0.04228346 -1.42622647]
[ 0.01501984  1.20039692 -0.07080799 -1.73181909]
[ 0.03902778  1.39625222 -0.10544438 -2.04566604]
[ 0.06695283  1.20235877 -0.1463577  -1.78738445]
[ 0.091       1.00915208 -0.18210539 -1.54354854]
Episode finished after 14 timesteps
[-0.0399665   0.01260257  0.0245506  -0.01353646]
[-0.03971445 -0.18286271  0.02427987  0.28679026]
[-0.0433717  -0.37832236  0.03001567  0.58703089]
[-0.05093815 -0.57385154  0.04175629  0.88901584]
[-0.06241518 -0.76951451  0.05953661  1.19452724]
[-0.07780547 -

[ 0.07593168  0.59876576 -0.06750321 -0.88159004]
[ 0.087907    0.40462245 -0.08513501 -0.61086918]
[ 0.09599945  0.21078717 -0.09735239 -0.34616877]
[ 0.10021519  0.40714938 -0.10427577 -0.66789384]
[ 0.10835818  0.2136202  -0.11763364 -0.40977843]
[ 0.11263058  0.41019632 -0.12582921 -0.73710944]
[ 0.12083451  0.21701606 -0.1405714  -0.48652623]
[ 0.12517483  0.41381253 -0.15030192 -0.82000117]
[ 0.13345108  0.22103185 -0.16670195 -0.57811288]
[ 0.13787172  0.41804949 -0.17826421 -0.91832625]
[ 0.14623271  0.22572687 -0.19663073 -0.68654648]
Episode finished after 24 timesteps
[-0.00562673 -0.04221526  0.02123278  0.03010958]
[-0.00647103 -0.23763517  0.02183497  0.32941533]
[-0.01122373 -0.43306104  0.02842328  0.62890323]
[-0.01988495 -0.62856788  0.04100134  0.93040036]
[-0.03245631 -0.43402259  0.05960935  0.6508787 ]
[-0.04113676 -0.62992191  0.07262692  0.96172054]
[-0.0537352  -0.43584717  0.09186133  0.6927094 ]
[-0.06245215 -0.63211536  0.10571552  1.01283966]
[-0.07509445 -

[ 0.05496782  0.76677877 -0.06562874 -1.25985382]
[ 0.07030339  0.96267603 -0.09082581 -1.57234812]
[ 0.08955692  1.1587566  -0.12227278 -1.89192276]
[ 0.11273205  1.35497519 -0.16011123 -2.21991188]
[ 0.13983155  1.16170337 -0.20450947 -1.98058404]
Episode finished after 19 timesteps


In [5]:
print(env.action_space)

Discrete(2)


In [6]:
print(env.observation_space)

Box(4,)


In [7]:
print(env.observation_space.high)

[  4.80000000e+00   3.40282347e+38   4.18879020e-01   3.40282347e+38]


In [8]:
print(env.observation_space.low)

[ -4.80000000e+00  -3.40282347e+38  -4.18879020e-01  -3.40282347e+38]


In [9]:
import numpy as np

In [13]:
np.argmax(np.array([1,2,2],))

1

In [14]:
aa = np.array([1,2,3,3])

In [15]:
aa == max(aa)

array([False, False,  True,  True], dtype=bool)

In [16]:
np.sum(aa == max(aa))

2

In [23]:
np.random.choice(aa==max(aa))

False

In [37]:
a = np.where(aa==max(aa))[0]

(array([2, 3]),)

In [36]:
a[0]

array([2, 3])

In [42]:
np.max(np.array([1,2]))

2

In [44]:
import gym

In [45]:
env = gym.make('FrozenLake-v0')

In [46]:
env.action_space.n

4

In [47]:
4 * 1/5

0.8

In [48]:
aa

array([1, 2, 3, 3])

In [49]:
aa[1:1+1]

array([2])

In [50]:
aa = np.identity(2)

In [51]:
aa

array([[ 1.,  0.],
       [ 0.,  1.]])

In [52]:
np.argmax(aa,1)

array([0, 1])